# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

on:
  workflow_run:
    workflows: ["Code Coverage"]
    types: [completed]

jobs:
  docs-verify:
    uses: eclipse-score/cicd-workflows/.github/workflows/docs-verify.yml@main
    permissions:
      pull-requests: write
      contents: read
    with:
      bazel-docs-verify-target: "//:docs_check"
  fetch-testlogs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download test logs from Code Coverage run
        uses: actions/download-artifact@v4
        with:
          name: bazel-testlogs
          path: bazel-testlogs
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Re-upload test logs for docs build
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: bazel-testlogs/
          retention-days: 10
  build-docs:
    needs: fetch-testlogs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: eclipse-score/cicd-workflows/.github/workflows/docs.yml@main
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write

    with:
      # the bazel-target depends on your repo specific docs_targets configuration (e.g. "suffix")
      bazel-target: "//:docs -- --github_user=${{ github.repository_owner }} --github_repo=${{ github.event.repository.name }}"
      retention-days: 3
      tests-report-artifact: bazel-testlogs
